### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by hbcohen2002** [nohajc/netflix-mitm-proxy#10]
Used this script before and it works great.  Trying to install on a new machine and having problems.  Can't get past the mitmproxy install.  I installed python and did "pip install mitmproxy" and get the following error.  Googled pep517 problems, but no luck.  the Microsoft vc++ runtime is there.  You need to install from the command line and not use the windows installer, correct?

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\User\AppData\Local\Temp\tmpsvne2_im'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-z6836gfh\zstandard_e0d3a753a498453d8a400a216e5bf8b2
  Complete output (26 lines):
  Traceback (most recent call last):
    File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-1b0j85t_\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-1b0j85t_\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-1b0j85t_\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-1b0j85t_\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 90, in <module>
      setup_zstd.get_c_extension(
    File "C:\Users\User\AppData\Local\Temp\pip-install-z6836gfh\zstandard_e0d3a753a498453d8a400a216e5bf8b2\setup_zstd.py", line 82, in get_c_extension
      compiler.initialize()
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-1b0j85t_\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 224, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-1b0j85t_\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\User\AppData\Local\Temp\pip-build-env-1b0j85t_\overlay\Lib\site-packages\setuptools\msvc.py", line 270, in _msvc14_get_vc_env
      raise distutils.errors.DistutilsPlatformError(
  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by nohajc** [comment]
Ok, Microsoft Visual C++ 14.0 or greater. That should be Visual Studio >= 2015.
I am unable to reproduce... Can you try Linux (or WSL) instead? It's generally less painful in my experience.
